"""Initial migration with all tables

Revision ID: b768d8325d92
Revises: 
Create Date: 2025-03-28 16:19:26.132323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b768d8325d92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('appointments_doctor_id_appointment_date_appointment_time_key', type_='unique')
        batch_op.create_unique_constraint('uix_doctor_appointment', ['doctor_id', 'appointment_date', 'appointment_time'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('uix_doctor_appointment', type_='unique')
        batch_op.create_unique_constraint('appointments_doctor_id_appointment_date_appointment_time_key', ['doctor_id', 'appointment_date', 'appointment_time'])

    # ### end Alembic commands ###
